# Generated by Django 5.2.5 on 2025-08-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название места или мероприятия')),
                ('description_short', models.TextField(max_length=300, verbose_name='Краткое описание (до 300 символов)')),
                ('description_long', models.TextField(verbose_name='Подробное описание')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lng', models.FloatField(verbose_name='Долгота')),
            ],
        ),
    ]
