# Generated by Django 5.2.5 on 2025-08-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_description_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='description',
        ),
    ]
