# Generated by Django 5.2.5 on 2025-08-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_placeimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(verbose_name='Краткое описание (до 255 символов)'),
        ),
    ]
