# Generated by Django 5.2.5 on 2025-08-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_place_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to='places/', verbose_name='Директория для сохранения изображений'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер картинки в галерее'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Место или событие, к которому относится изображение'),
        ),
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['place', 'order'], name='places_plac_place_i_132bbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('title', 'lat', 'lng'), name='unique_place_title_lat_lng'),
        ),
    ]
