# Generated by Django 5.2.5 on 2025-08-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_short_description_alter_placeimage_image_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['order'], name='places_plac_order_66e296_idx'),
        ),
    ]
